services:
# Crawler service
  spider-crawler:
   build: .
   container_name: arcnetic_spider
   volumes:
     - .:/app
   depends_on:
      local-db:
        condition: service_healthy
   env_file:
      - .env
   environment:
      DATABASE_URL: ${DATABASE_URL}
      TARGET_URL: ${TARGET_URL}

#localdb service
  local-db:
   image: postgres:15-alpine
   container_name: spider_db
   env_file:
      - .env
   environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
   ports:
      - "5432:5432"
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
      timeout: 3s